from langchain_core.messages import HumanMessage
from langchain.agents import create_agent
from langchain_ollama import ChatOllama

from langchain_community.utilities import SQLDatabase
from langchain_community.agent_toolkits import SQLDatabaseToolkit
from langchain_community.agent_toolkits import SQLDatabaseToolkit, create_sql_agent

from app.mcp.tools.calculator_tool import calculator
from app.mcp.tools.filesystem_tools import list_project_files
from app.mcp.tools.tavily_search import web_search
from app.core.config import settings
from app.prompts.system_prompts import AGENT_SYSTEM_PROMPT


from app.core import config
from openai.types.responses import response
from langchain_core.messages import HumanMessage


# Agent Service
class AgentService:
    """
    Service class responsible for coordinating and running multi-agent AI tasks.

    This service initializes the language model (LLM), registers available tools,
    and configures a LangChain agent using the Zero-Shot ReAct description strategy
    to execute complex queries.
    """

    def __init__(self):
        """
        Initializes the AgentService, setting up the LLM, registering tools,
        and building the primary ReAct agent executors.
        """
        self.model = ChatOllama(model=settings.OLLAMA_MODEL, temperature=0)

        self.db = SQLDatabase.from_uri(
            "sqlite:///app/database/sample.db"
        )

        self.toolkit = SQLDatabaseToolkit(
            db=self.db,
            llm=self.model
        )
        
        # Pre-initialize agent with web search
        self.agent = create_agent(
            tools=[calculator, web_search, list_project_files],
            model=self.model,
            system_prompt=AGENT_SYSTEM_PROMPT
        )

       
        self.sql_agent = create_sql_agent(
            llm=self.model,
            toolkit=self.toolkit,
            verbose=False,
            handle_parsing_errors=True
        )
        self.sql_agent.handle_parsing_errors = True

    # simple chat function
    def run_chat(self, prompt: str) -> str:
        """
        Simple chat function that uses the LLM to generate a response.

        Args:
            prompt (str): The user query or task description for the agent.

        Returns:
            str: The output response generated by the agent.
            """
        result = self.model.invoke(prompt)
        return result.content


    # Run Agent
    def run_agent(self, prompt: str) -> str:
        """
        Executes the agent with a given prompt and returns the output.

        Args:
            prompt (str): The user query or task description for the agent.

        Returns:
            str: The output response generated by the agent.
            """
        active_agent = self.agent
        response = active_agent.invoke({"messages": [HumanMessage(content=prompt)]})

        # LangGraph returns the full state dictionary containing the messages list.
        # The final answer is the content of the last message (AIMessage) in that list.
        return response["messages"][-1].content


    def run_sql_agent(self, prompt: str) -> str:
        """
        Executes the SQL agent with a given prompt and returns the output.

        Args:
            prompt (str): The user query or task description for the agent.

        Returns:
            str: The output response generated by the agent.
            """
        response = self.sql_agent.run({"messages": [HumanMessage(content=prompt)]})
        return response["messages"][-1].content
    
    
    def run_orchestrator(self, message: str):
        """
        Executes the orchestrator with a given prompt and returns the output.

        Args:
            prompt (str): The user query or task description for the agent.

        Returns:
            str: The output response generated by the agent.
        """

        from app.workflows.graph_builder import graph

        response = graph.invoke(
            {
                "messages": [HumanMessage(content=message)]
            }
        )
        
        if response.get("final_response"):
            return response["final_response"]
        elif response.get("sql_result"):
            return response["sql_result"]
        elif response.get("rag_result"):
            return response["rag_result"]
        elif response.get("research_result"):
            return response["research_result"]

        return response["messages"][-1].content


agent_service = AgentService()