from langchain_core.messages import HumanMessage
from langchain.agents import create_agent
from langchain_ollama import ChatOllama

from app.tools.calculator.calculator_tool import calculator
from app.tools.web_search.tavily_search import web_search
from app.core.config import settings
from app.services.llm_service import LLMService
from app.prompts.system_prompts import AGENT_SYSTEM_PROMPT

# Agent Service
class AgentService:
    """
    Service class responsible for coordinating and running multi-agent AI tasks.

    This service initializes the language model (LLM), registers available tools,
    and configures a LangChain agent using the Zero-Shot ReAct description strategy
    to execute complex queries.
    """

    def __init__(self):
        """
        Initializes the AgentService, setting up the LLM, registering tools,
        and building the primary ReAct agent executors.
        """

        model = ChatOllama(model=settings.OLLAMA_MODEL, temperature=0)
    
        # Initialize LLM
        self.llm = model

        # Pre-initialize agent with web search
        self.agent_with_search = create_agent(
            tools=[calculator, web_search],
            model=self.llm,
            system_prompt=AGENT_SYSTEM_PROMPT
        )

        # Pre-initialize agent without web search
        self.agent_without_search = create_agent(
            tools=[calculator],
            model=self.llm,
            system_prompt=AGENT_SYSTEM_PROMPT
        )

        # Retain self.agent for backward compatibility
        self.agent = self.agent_with_search

    # Run Agent
    def run(self, prompt: str) -> str:
        """
        Executes the agent with a given prompt and returns the output.

        Args:
            prompt (str): The user query or task description for the agent.

        Returns:
            str: The output response generated by the agent.
            """
        active_agent = self.agent
        response = active_agent.invoke({"messages": [HumanMessage(content=prompt)]})

        # LangGraph returns the full state dictionary containing the messages list.
        # The final answer is the content of the last message (AIMessage) in that list.
        return response["messages"][-1].content


agent_service = AgentService()